name: Build & Test
on:
  workflow_call:
  pull_request:
  push:

jobs:
  checks:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Installing toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
            command: clippy
            args: -- -D warnings

  test:
    name: Test Suite
    needs: checks
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, nightly]
    runs-on: ${{ matrix.os }}
    env:
        TOOLCHAIN: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Installing toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

#   coverage:
#     name: Coverage
#     needs: test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout sources
#         uses: actions/checkout@v5



#       - name: Installing toolchain
#         uses: actions-rust-lang/setup-rust-toolchain@v1
#         with:
#           components: llvm-tools-preview
#           override: true

#       - name: Download grcov
#         uses: actions-rs/cargo@v1
#         with:
#           command: install
#           args: grcov

#       - name: Run xtask coverage
#         uses: actions-rs/cargo@v1
#         with:
#           command: xtask
#           args: coverage

#       - name: Upload coverage reports to Codecov
#         uses: codecov/codecov-action@v4.0.1
#         with:
#           token: ${{ secrets.CODECOV_TOKEN }}
#           slug: ejmount/ebnf-omnitool
